<a href="https://colab.research.google.com/github/kirillspiney/projects/blob/main/pandas_numpy/w_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Задание 1
Создайте numpy array с элементами от числа N до 0. Например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [ ]:
import numpy as np

N = 10
arr = np.arange(N-1, -1, -1)
print(arr)

[9 8 7 6 5 4 3 2 1 0]


Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму её значений на диагонали.

In [ ]:
import numpy as np

N = 10
diag_arr = np.diag(np.arange(N, -1, -1))
diag_sum = np.trace(diag_arr)
print(diag_arr)
print(diag_sum)

[[10  0  0  0  0  0  0  0  0  0  0]
 [ 0  9  0  0  0  0  0  0  0  0  0]
 [ 0  0  8  0  0  0  0  0  0  0  0]
 [ 0  0  0  7  0  0  0  0  0  0  0]
 [ 0  0  0  0  6  0  0  0  0  0  0]
 [ 0  0  0  0  0  5  0  0  0  0  0]
 [ 0  0  0  0  0  0  4  0  0  0  0]
 [ 0  0  0  0  0  0  0  3  0  0  0]
 [ 0  0  0  0  0  0  0  0  2  0  0]
 [ 0  0  0  0  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]]
55


Задание 3
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [ ]:
import numpy as np

A = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])

B = np.array([4, 12, -3])

X = np.linalg.solve(A, B)

print("x = ", X[0])
print("y = ", X[1])
print("z = ", X[2])

x =  0.4666666666666668
y =  3.844444444444444
z =  -5.555555555555555


Задание 4. Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)
На сайт заходит очередной посетитель, о покупках которого известно следующее:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [ ]:
#с доп. библиотекой
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

users_stats = np.array([
    [2, 1, 0, 0, 0, 0],
    [1, 1, 2, 1, 0, 0],
    [2, 0, 1, 0, 0, 0],
    [1, 1, 2, 1, 0, 1],
    [0, 0, 1, 2, 0, 0],
    [0, 0, 0, 0, 0, 5],
    [1, 0, 0, 0, 0, 0],
    [0, 1, 1, 0, 0, 0],
    [0, 0, 0, 1, 1, 3],
    [1, 0, 0, 2, 1, 4]
], np.int32)

next_user_stats = np.array([0, 1, 2, 0, 0, 0])

similarities = []

for user_stats in users_stats:
    similarity = cosine_similarity([next_user_stats], [user_stats])
    similarities.append(similarity[0][0])

most_similar_user_index = np.argmax(similarities)

print("Самый похожий пользователь имеет индекс:", most_similar_user_index)
print("Значение косинусного сходства:", similarities[most_similar_user_index])

Самый похожий пользователь имеет индекс: 7
Значение косинусного сходства: 0.9486832980505137


In [ ]:
#только numpy
import numpy as np

users_stats = np.array([
    [2, 1, 0, 0, 0, 0],
    [1, 1, 2, 1, 0, 0],
    [2, 0, 1, 0, 0, 0],
    [1, 1, 2, 1, 0, 1],
    [0, 0, 1, 2, 0, 0],
    [0, 0, 0, 0, 0, 5],
    [1, 0, 0, 0, 0, 0],
    [0, 1, 1, 0, 0, 0],
    [0, 0, 0, 1, 1, 3],
    [1, 0, 0, 2, 1, 4]
], np.int32)

next_user_stats = np.array([0, 1, 2, 0, 0, 0])

similarities = []

for user_stats in users_stats:
    dot_product = np.dot(next_user_stats, user_stats)
    norm_next_user_stats = np.linalg.norm(next_user_stats)
    norm_user_stats = np.linalg.norm(user_stats)
    similarity = dot_product / (norm_next_user_stats * norm_user_stats)
    similarities.append(similarity)

most_similar_user_index = np.argmax(similarities)

print("Самый похожий пользователь имеет индекс:", most_similar_user_index)
print("Значение косинусного сходства:", similarities[most_similar_user_index])

Самый похожий пользователь имеет индекс: 7
Значение косинусного сходства: 0.9486832980505138
